### ISSUE TITLE
Use git repositories

### ISSUE THREAD

**Issue by CoolOppo** [moovweb/gvm#111]
Golang has officially made the switch from Mercurial to git. GVM needs to be updated with respect to that, and mercurial needs to be removed from the requirements as a result.

**Comment by shuhaowu** [comment]
Is this project still maintained?

**Comment by twojtasz** [comment]
Yes,  it is being maintained, but it has hit a slow period.  We will be catching up soon.  Sorry for this delay in PR reviews.

**Comment by jbussdieker** [comment]
+1

**Comment by codeslinger** [comment]
:+1:

**Comment by CoolOppo** [comment]
![Shh.](http://i.imgur.com/MZVgM27.gif)

**Comment by twojtasz** [comment]
Thanks.  Last I checked the Go team still recommended using the mercurial
repo for installation, but dev has fully moved to github.  I'll double
check the official recommendation and if necessary post to go-nuts ml if I
don't find a concrete answer.

Once I have more info I'll post an update.

Cheers,
TimW

**Comment by CoolOppo** [comment]
Sounds good. Honestly, it doesn't really matter what they recommend. There's no need to be pedantic about it; you'll lose nothing from switching to Git (other than Mercurial), and all of the releases of Go are available on [the releases page](https://github.com/golang/go/releases), showing us that the repo is fully capable.

**Comment by jbussdieker** [comment]
+1

**Comment by mattyb** [comment]
They no longer recommend mercurial: https://golang.org/doc/install/source#fetch
Further, go1.4.1 has been released on github but is not tagged as a release on mercurial, so `gvm install go1.4.1` reports it as an invalid version. GVM is broken.

**Comment by everbeen** [comment]
+1

> mattyb commented 4 days ago
> 
> They no longer recommend mercurial: https://golang.org/doc/install/source#fetch
Further, go1.4.1 has been released on github but is not tagged as a release on mercurial, so gvm install go1.4.1 reports it as an invalid version. GVM is broken.

**Comment by bsm** [comment]
+1

**Comment by chrisprobst** [comment]
+1

**Comment by gregorygtseng** [comment]
This should be resolved. Please try the latest gvm and let us know if there are any issues.

**Comment by shuhaowu** [comment]
The version "release" is no longer available.
