### ISSUE TITLE
Curl dependency

### ISSUE THREAD

**Issue by DanielHeath** [moovweb/gvm#117]
GVM depends on curl, which is not installed by default on ubuntu. 

GVM could check for curl the same way it checks for bison/mercurial.

**Comment by runcom** [comment]
https://github.com/moovweb/gvm.git

**Comment by DanielHeath** [comment]
?

**Comment by runcom** [comment]
sorry, i've updated my post, master is broken though and tests fail

**Comment by gregorygtseng** [comment]
fixed
