### ISSUE TITLE
I think there is already a gvm, the "http://gvmtool.net/", how about change to "govm"?

### ISSUE THREAD

**Issue by liuchong** [moovweb/gvm#146]
I think there is already a gvm, the "http://gvmtool.net/"
why not let call this gvm as "govm"?
Actually I think this gvm should be ealier, since graphs of github, "Nov 13, 2011 – Jul 20, 2015" against "Aug 26, 2012 – Jul 20, 2015 https://github.com/gvmtool/gvm-cli/graphs/contributors", but seems "govm" is better than "groovyvm", so the change of this gvm should be better?

**Comment by grossjonas** [comment]
+1
