### ISSUE TITLE
gvm install go1.5beta2 error  on mac os? 

### ISSUE THREAD

**Issue by pengswift** [moovweb/gvm#149]
install log:
```log
##### Building Go bootstrap tool.
cmd/dist
ERROR: Cannot find /Users/liupeng/go1.4/bin/go.
Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
./make.bash: line 121: /Users/liupeng/go1.4/bin/go: No such file or directory
```

**Comment by gedw99** [comment]
i got the same thing if i recall. 
i installed go 1.4 the traditional way. This acts as a bootstrap, so you can then install and run gvm.

if the maintainer can correct me if i am wrong please, as all i know is that this is what fixed things for me

**Comment by gedw99** [comment]
also gvm is amrt enough to knwo that the manually installed go 1.4 is not installed by itself.
when you do "gvm list" it will show it as "system"
very nice

**Comment by azr** [comment]
`export GOROOT_BOOTSTRAP=$GOROOT` made it for me !

**Comment by loose11** [comment]
Is it not possible to add this to the gvm install script? +1

**Comment by mvadu** [comment]
awesome! thank you, was facing same error on Pi 2.
