### ISSUE TITLE
gvm fails to install go1.5 binary on mac 

### ISSUE THREAD

**Issue by jonasi** [moovweb/gvm#152]
go no longer serves distinct `10.6` and `10.8` and builds for 1.5 (and future versions, I would imagine).  So the new dl url is

```
http://golang.org/dl/go1.5.darwin-amd64.tar.gz
```

rather than

```
http://golang.org/dl/go1.5.darwin-amd64-osx10.8.tar.gz
```

**Comment by joshuataylor** [comment]
Same as on Linux (obviously) :)
