### ISSUE TITLE
Error with go1.5 install

### ISSUE THREAD

**Issue by 1xch** [moovweb/gvm#155]
```
~  gvm install go1.5                                                                                                                                
Installing go1.5...
 * Compiling...
ERROR: Failed to compile. Check the logs at /home/xxxxx/.gvm/logs/go-go1.5-compile.log
ERROR: Failed to use installed version
~ cat /home/xxxxx/.gvm/logs/go-go1.5-compile.log                                                                                                   
##### Building Go bootstrap tool.
cmd/dist
ERROR: Cannot find /home/xxxxx/go1.4/bin/go.
Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
./make.bash: line 121: /home/xxxxx/go1.4/bin/go: No such file or directory
```

**Comment by dariusc93** [comment]
You will need go1.4 installed before you can install go1.5 (since this is compiling from go source and 1.5 doesnt use C anymore) run `export $GOROOT_BOOTSTRAP=$GOROOT` then run `gvm install go1.5`

**Comment by oryband** [comment]
:+1:

**Comment by jameshueston** [comment]
The compiler log: "ERROR: Cannot find /home/xxxxx/go1.4/bin/go"
made me think I should ```export GOROOT_BOOTSTAP="/home/username/.gvm/gos/go1.4.x/bin"```
since it was looking for the binary; revision suggested:
```Set $GOROOT_BOOTSTRAP to [the root (not the bin) of] a working Go tree >= Go 1.4.```

**Comment by Zamicol** [comment]
@dariusc93's solution worked.  Thanks.  

gvm install go1.4 
gvm use go1.4 
export GOROOT_BOOTSTRAP=$GOROOT 
gvm install go1.5

**Comment by davpow** [comment]
Thanks @dariusc93.  Your solution fixed the problem.
``` bash
gvm install go1.4 
gvm use go1.4 
export GOROOT_BOOTSTRAP=$GOROOT 
gvm install go1.5
```

**Comment by sudhirvkumar** [comment]
Why can't it use go1.4.2? I already had go1.4.2 installed!

**Comment by dariusc93** [comment]
@sudhirvkumar what do you mean?

**Comment by surajx** [comment]
if you are on 1.4.x, you need to export `GOROOT_BOOTSTRAP` before installing go1.5
``` bash
export GOROOT_BOOTSTRAP=$GOROOT
```

**Comment by ToddGreenstein** [comment]
I hit the same issue, and @dariusc93 solution worked for me.  Thank you for posting this.

**Comment by jessecogollo** [comment]
@dariusc93 solution worked for me.

**Comment by trkrameshkumar** [comment]
Thanks @dariusc93. your solution works

**Comment by akwmak** [comment]
I followed the instruction to install 1.4 first and then 1.5. It failed to complie and had the following log:



go build bootstrap/compile/internal/gc: /home/vagrant/.gvm/gos/go1.4/pkg/tool/linux_amd64/6g: signal: killed
bootstrap/link/internal/ld
bootstrap/link/internal/amd64
bootstrap/link/internal/arm
bootstrap/link/internal/arm64
bootstrap/link/internal/ppc64
bootstrap/link/internal/x86
bootstrap/link
go tool dist: FAILED: /home/vagrant/.gvm/gos/go1.4/bin/go install -v bootstrap/...: exit status 1

**Comment by unnikked** [comment]
@akwmak same issue here.

I managed to solve it by

```
sudo apt-get update
sudo apt-get upgrade
```

**Comment by huoshiqiu** [comment]
@dariusc93 solution worked for me too! Thx

**Comment by randall-mo** [comment]
@dariusc93  BUT, once I failed to install go1.5, I cannot install go 1.4.


[root@zoo1 ~]# gvm install go1.4                       
Installing go1.4...
 * Compiling...
ERROR: Failed to compile. Check the logs at /root/.gvm/logs/go-go1.4-compile.log
ERROR: Failed to use installed version
[root@zoo1 ~]# cat /root/.gvm/logs/go-go1.4-compile.log 
##### Building Go bootstrap tool.
cmd/dist
ERROR: Cannot find /root/go1.4/bin/go.
Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.

**Comment by willin** [comment]
```
[proxychains] DLL init: proxychains-ng 4.10
# Building C bootstrap tool.
cmd/dist

# Building compilers and Go bootstrap tool for host, darwin/amd64.
lib9
libbio
liblink
cmd/cc
cmd/gc
cmd/6l
cmd/6a
cmd/6c
cmd/6g
runtime
errors
sync/atomic
sync
io
unicode
unicode/utf8
unicode/utf16
bytes
math
strings
strconv
bufio
sort
container/heap
encoding/base64
syscall
time
os
reflect
fmt
encoding
encoding/json
flag
path/filepath
path
io/ioutil
log
regexp/syntax
regexp
go/token
go/scanner
go/ast
go/parser
os/exec
os/signal
net/url
text/template/parse
text/template
go/doc
go/build
cmd/go
fatal error: runtime: bsdthread_register error (unset DYLD_INSERT_LIBRARIES)

runtime stack:
runtime.throw(0x3e7855)
	/Users/willin/.gvm/gos/go1.4/src/runtime/panic.go:491 +0xad fp=0x7fff5fbff660 sp=0x7fff5fbff630
runtime.goenvs()
	/Users/willin/.gvm/gos/go1.4/src/runtime/os_darwin.c:103 +0x60 fp=0x7fff5fbff678 sp=0x7fff5fbff660
runtime.schedinit()
	/Users/willin/.gvm/gos/go1.4/src/runtime/proc.c:141 +0x5f fp=0x7fff5fbff6a0 sp=0x7fff5fbff678
runtime.rt0_go(0x7fff5fbff6d0, 0x4, 0x7fff5fbff6d0, 0x0, 0x4, 0x7fff5fbff8b8, 0x7fff5fbff8f8, 0x7fff5fbff8fe, 0x7fff5fbff901, 0x0, ...)
	/Users/willin/.gvm/gos/go1.4/src/runtime/asm_amd64.s:95 +0x116 fp=0x7fff5fbff6a8 sp=0x7fff5fbff6a0
```

what's wrong

**Comment by mitghi** [comment]
@akwmak 
Any success ? I have the same problem and i followed what @akwmak wrote.It did not fixed the issue.

**Comment by sudhirvkumar** [comment]
I just installed binary version.

**Comment by technowar** [comment]
@akwmak @mitghi any success on this error?

**Comment by algaio** [comment]
@akwmak @mitghi Same situation here, even after using the recommendation from @unnikked

**Comment by algaio** [comment]
@technowar @akwmak @mitghi 

I got around this issue by:
- reinstalling Jessie Lite
- sudo apt-get update
- sudo apt-get upgrade
- sudo apt-get install curl git mercurial make binutils bison gcc build-essential
- bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
- exit
- gvm install go1.4
- gvm use go1.4 --default
- gvm install go1.5.1
- gvm use go1.5.1 --default

Still can't explain why we had the issue above, but atlas this will get you started.

**Comment by technowar** [comment]
@algaio @akwmak @mitghi I solved mine by increasing my VM's RAM to `2048`. It seemed like mine failed to install `go1.4.3`.

**Comment by algaio** [comment]
@technowar Oh cool... mine was failing when trying to install go1.5 upwards.

**Comment by benzsuankularb** [comment]
@algaio @akwmak @mitghi 
I followed @technowar by release RAM from mongodb then it's work.
My droplet is just 500MB

**Comment by jesusjjf** [comment]
You can also set `GOROOT_BOOTSTRAP` to always use your Go 1.4 so you don't have to switch it in GVM.
```
export GOROOT_BOOTSTRAP="/Users/{username}/.gvm/gos/go1.4"
```

**Comment by tejasmanohar** [comment]
So this works but is it not possible to bootstrap latest go without 1.4?

**Comment by johndpope** [comment]
thanks @dariusc93 - I needed to update this for it to work. 
gvm install go1.4 **-B** 
gvm use go1.4 
export GOROOT_BOOTSTRAP=$GOROOT

**Comment by IgorGanapolsky** [comment]
Are we always gonna have to install **go1.4** in order to install later versions?  I mean, I'm trying to install **1.7** now, and this is still the case...

**Comment by technowar** [comment]
@IgorGanapolsky Yes. Actually, it is written in their README.

```
A Note on Compiling Go 1.5
Go 1.5+ removed the C compilers from the toolchain and replaced them with one written in Go. Obviously, this creates a bootstrapping problem if you don't already have a working Go install. In order to compile Go 1.5+, make sure Go 1.4 is installed first.
```

**Comment by Qard** [comment]
I'm trying to install 1.7.1, but need 1.4 to build it, so I tried installing that, however El Capitan seems to *also* be incapable of installing any version before go1.5. Here's the log for 1.4:

```
# Building C bootstrap tool.
cmd/dist

# Building compilers and Go bootstrap tool for host, darwin/amd64.
lib9
libbio
liblink
cmd/cc
cmd/gc
cmd/6l
cmd/6a
cmd/6c
/Users/stephenbelanger/.gvm/gos/go1.4/src/cmd/6c/txt.c:995:28: error: shifting a negative signed value is undefined [-Werror,-Wshift-negative-value]
/Users/stephenbelanger/.gvm/gos/go1.4/src/cmd/6c/txt.c:1045:28: error: shifting a negative signed value is undefined [-Werror,-Wshift-negative-value]
go tool dist: FAILED: clang -Wall -Wstrict-prototypes -Wextra -Wunused -Wno-sign-compare -Wno-missing-braces -Wno-parentheses -Wno-unknown-pragmas -Wno-switch -Wno-comment -Wno-missing-field-initializers -Werror -fno-common -ggdb -pipe -Wuninitialized -O2 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -mmacosx-version-min=10.6 -c -m64 -I /Users/stephenbelanger/.gvm/gos/go1.4/include -I /Users/stephenbelanger/.gvm/gos/go1.4/src/cmd/6c -o /Users/stephenbelanger/.gvm/gos/go1.4/pkg/obj/cmd/6c/txt.o /Users/stephenbelanger/.gvm/gos/go1.4/src/cmd/6c/txt.c
```

I literally can not install *any* version available through gvm, so gvm is kind of useless to me right now. 😭

**Comment by technowar** [comment]
Did you install it using `-B` option?

**Comment by windhost** [comment]
@Qard 
https://github.com/moovweb/gvm/pull/176/commits/6d99f7dee6ddd09992620654c2067aaf869b3d1c
