### ISSUE TITLE
ERROR: Unrecognized Go version

### ISSUE THREAD

**Issue by jackzampolin** [moovweb/gvm#160]
I have installed gvm using: 

```
bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
```

After restarting my terminal I try to use:

```
gvm install go1.4
```

and get the following output:

```
Downloading Go source...
Updating Go source...
ERROR: Unrecognized Go version
```

GVM is v1.0.22.  I have mercurial installed on my system as well as xcode dev-tools

**Comment by matthewjosephtaylor** [comment]
Same error I'm using docker ubuntu latest. Go Version Manager v1.0.22 installed at /home/user/.gvm

**Comment by Zilev** [comment]
I'm having the same error, any idea? thanks in advance

**Comment by AlexAznar** [comment]
gvm install go1.4.2
gvm use go1.4.2

it's works for me

**Comment by sunloverz** [comment]
+

**Comment by mishak87** [comment]
I had the same error. It seemed that gvm did't update version list. I had not used it for few months. rm -rf and install fixed it :smile:

**Comment by IgorGanapolsky** [comment]
@mishak87 If I remove **.gvm**, then I'll have to completely reinstall GVM.

**Comment by mezoni** [comment]
Specifying the default version should help

```
gvm use go1.7.4 --default
```

**Comment by lestrrat** [comment]
FYI, this just happened to me. After a little digging around I did

```
cd ~/.gvm/archive/go
git pull --tags
```

Then after tags were pulled in, `gvm install go1.9.3` worked.

**Comment by BenKnigge** [comment]
Not sure if this is still an issue but I plan on looking into it.

**Comment by migueleliasweb** [comment]
Still doesn't work for me =/

```
$ gvm install 1.4  
Updating Go source...
ERROR: Unrecognized Go version
```

```
$ gvm install go1.4.2
Installing go1.4.2...
 * Compiling...
/root/.gvm/scripts/install: line 84: go: command not found
ERROR: Failed to compile. Check the logs at /root/.gvm/logs/go-go1.4.2-compile.log
ERROR: Failed to use installed version
```

**Comment by besteffects** [comment]
log:
error: implicit conversion from 'int' to 'char' changes value from 156 to -100 [-Werror,-Wconstant-conversion]

**Comment by besteffects** [comment]
Tried with go1.14.4 and go1.4.2

**Comment by pmalek** [comment]
Please take a look at https://github.com/moovweb/gvm/pull/354. I've also had this problem but this small patch seemed to have fixed it (TLDR: when installing new version it runs `git pull` without `--tags` hence not downloading new release tags).

**Comment by pakistancan** [comment]
check if `GREP_OPTIONS` is set to `--color=always`, either set this to `--color=never` 
or 
edit following scripts

`~/.gvm/scripts/install`
`~/.gvm/scripts/env/use`

and add `--color=never` to all the places where `$GREP_PATH` is used

**Comment by stevem995** [comment]
Still broken on mac....

gvm install go1.16.5
Installing go1.16.5...
 * Compiling...
/Users/XXXXXXX/.gvm/scripts/install: line 84: go: command not found
ERROR: Failed to compile. Check the logs at /Users/XXXXXXX/.gvm/logs/go-go1.16.5-compile.log
ERROR: Failed to use installed version

**Comment by pmalek** [comment]
Still works for me using what I've proposed in #354

**Comment by pakistancan** [comment]
@stevem995 can you please check log and see what went wrong?

**Comment by stevem995** [comment]
I lost home internet. Will try to check tomorrow. 

On July 6, 2021 1:51:48 PM EDT, Ali ***@***.***> wrote:
***@***.*** can you please check log and see what went wrong?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/moovweb/gvm/issues/160#issuecomment-874963069

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by austincunningham** [comment]
New machine was hitting the same issues with gvm v1.0.22,  depending on the go version .

As there was no go on the sytem, installed the initial version https://go.dev/doc/install and `gvm install` started to function after that.
