### ISSUE TITLE
Can not install 1.5.x

### ISSUE THREAD

**Issue by azer** [moovweb/gvm#166]
It doesn't recognize any of these as a valid version input;

1.5.1 
1.5
go1.5
go1.5.1
v1.5
v1.5.1

```
  λ  gvm install go1.5
Updating Go source...
ERROR: Unrecognized Go version
```

**Comment by dustinrc** [comment]
I initially ran into this issue, as well. A (workaround) solution is to execute `gvm use system` first and then `gvm install go1.5.1`.

**Comment by ineiti** [comment]
And what if there is NO go in the system at all? I just tried to install it on a barebones Ubuntu1404 (with the compiler and make), but I just get the error

```
:~$ gvm install go1.4
Downloading Go source...
Installing go1.4...
 * Compiling...
ERROR: Failed to compile. Check the logs at /home/dedis/.gvm/logs/go-go1.4-compile.log
ERROR: Failed to use installed version
```

**Comment by dustinrc** [comment]
Not verified, but I would think `gvm install go1.4 --binary`.

**Comment by dmitry** [comment]
What I've tried and it works:

```
gvm install 1.4.2
gvm use 1.4.2
gvm install go1.5.1
```

**Comment by denispeplin** [comment]
Thank you @dmitry, it works!
Full list of commands I've used:

```
gvm install go1.4.3
gvm use go1.4.3
gvm install go1.5.2
gvm use go1.5.2
```
