### ISSUE TITLE
change the download url

### ISSUE THREAD

**Issue by zongUMR** [moovweb/gvm#172]
Hi, I am in China and i cant link to the https://go.googlesource.com/go.
So a better address to replace it??
thanks

**Comment by wahyd4** [comment]
Yeah, due to the Google connecting issue in China. We can't use gvm at all.
Can you guys give a chance to let user change the repo url to 
github one?  https://github.com/golang/go

**Comment by whix** [comment]
same issue with yours, the url still is https://go.googlesource.com/go.

**Comment by dai99** [comment]
same problem in CHINA

**Comment by mosaic101** [comment]
我替换了下载源与版本获取源  https://github.com/mosaic101/gvm，使用方式不变

**Comment by BenKnigge** [comment]
The environment variable GO_BINARY_BASE_URL was created with the following commit. 

https://github.com/moovweb/gvm/commit/ed2c95bcafaa91c123ec3868570d07b8d6e8186c

**Comment by llqgit** [comment]
@BenKnigge It's not work for me. Is there a simple example somewhere?

**Comment by BenKnigge** [comment]
Will take a look in my morning. I haven't been able to make create a new release yet so you will need to clone the repo before trying.
