### ISSUE TITLE
gvm cannot find binary for 1.6 on OSX

### ISSUE THREAD

**Issue by tgandrews** [moovweb/gvm#195]
Running `gvm install go1.6 -B` on OSX 10.11.4

Returns the following error:

```
ERROR: Failed to download binary go from http://golang.org. Trying https://go.googlecode.com
ERROR: Failed to download binary go
```

It tries to access URL: `http://golang.org/dl/go1.6.darwin-amd64-osx10.8.tar.gz`

Fixing the install script so it no longer adds the OSX version seems to resolve the issue. And the url becomes `http://golang.org/dl/go1.6.darwin-amd64.tar.gz`.

I guess the `http://golang.org/dl/` format has changed.

**Comment by matiasinsaurralde** [comment]
Same problem here, running the same OSX version.

**Comment by paritosh90** [comment]
Is there any resolution on this?

**Comment by dave-tucker** [comment]
see https://github.com/moovweb/gvm/pull/214

**Comment by paritosh90** [comment]
@dave-tucker: Code stated above is not merged in master. Also 1 test case is failing.
@moovops : Pull request stated above by dave is still not closed/merged. Please fix this issue asap, because its restricting download of go1.5 and go1.6.
Please let me know the resolution.

**Comment by dave-tucker** [comment]
The failing tests seem unrelated. OSX tests have been broken on master for a while it seems

**Comment by BenKnigge** [comment]
This has been resolved in the following merged pr https://github.com/moovweb/gvm/pull/214
