### ISSUE TITLE
Failed to compile in Ubuntu 16.04

### ISSUE THREAD

**Issue by cchongXD** [moovweb/gvm#197]
Hi all,

I am unable to install go after upgraded to Ubuntu 16.04 using source. I have tried go version 1.6 and 1.4. It worked fine when I used --binary option to install it.

This is the output of the console:

$ gvm install go1.6
Downloading Go source...
Installing go1.6...
- Compiling...
  ERROR: Failed to compile. Check the logs at /home/myname/.gvm/logs/go-go1.6-compile.log
  ERROR: Failed to use installed version
  $

Please take a look. Thanks.

**Comment by cristian-sima** [comment]
+1

**Comment by Seraf** [comment]
Hello, try to set this in your env : `export CGO_ENABLED=0`

https://github.com/golang/go/issues/13114

**Comment by jhermann** [comment]
See the README regarding bootstrapping 1.5+ from a binary go1.4 install.

**Comment by prantlf** [comment]
`CGO_ENABLED=0` didn't help. I had to enable use GCC 4.8 before running `gvm install`.

Ubuntu 17.10.

**Comment by jhermann** [comment]
Try works on Xenial…
```sh
gvm_version=master # you may use a tag like "1.0.22" instead
 
# Install OS level dependencies (see the GVM README for other distros)
sudo apt-get install curl git mercurial make binutils bison gcc build-essential
 
# Install GVM
cd /tmp
curl -sOSL "https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer"
view gvm-installer # give the "gvm-installer" script a short review
bash gvm-installer "$gvm_version" "$HOME/.local"
. ~/.local/gvm/scripts/gvm
 
# Install bootstrapping version, alternatively you could do…
#   sudo apt-get install golang
#   export GOROOT_BOOTSTRAP=$(ls -1d /usr/lib/go-[0-9]* | tail -n1)
gvm install "go1.4" -B
gvm use "go1.4"
export GOROOT_BOOTSTRAP=$GOROOT
 
# List available go *release* versions
gvm listall | egrep 'go[.0-9]+$'
```
Now install any version you want.

**Comment by prantlf** [comment]
I repeated your steps with a fresh testing user. The "-B" was the key to succeed:

    gvm install "go1.4" -B

Initially, I didn't use the "-B' option. Although I started by installing "go1.4", which should be possible according to README, it failed. Installing 1.8.5 or 1.9.2 right away failed too. I suspect, that either `go` sources or the way how `gvm` compiles them, don't work with gcc 7. Or at least not in freshly installed Ubuntu 17.10 without any customizations. I forgot the default gcc version in Xenial. Was it 4.8?

You may want to document running `gvm install "go1.4" -B` before installing any newer version as a mandatory step as well... Or using gcc 4.8 and installing any `go` version as the first one.

Important errors:

```text
$ gvm install "go1.4"
Downloading Go source...
Installing go1.4...
 * Compiling...
ERROR: Failed to compile. Check the logs at /home/test/.local/gvm/logs/go-go1.4-compile.log
ERROR: Failed to use installed version

$ cat /home/test/.local/gvm/logs/go-go1.4-compile.log
# Building C bootstrap tool.
cmd/dist

# Building compilers and Go bootstrap tool for host, linux/amd64.
lib9
/home/test/.local/gvm/gos/go1.4/src/lib9/fmt/fltfmt.c: In function '__efgfmt':
/home/test/.local/gvm/gos/go1.4/src/lib9/fmt/fltfmt.c:437:5: error: this statement may fall through [-Werror=implicit-fallthrough=]
   if(ndigits > prec) {
     ^
/home/test/.local/gvm/gos/go1.4/src/lib9/fmt/fltfmt.c:451:2: note: here
  default:
  ^~~~~~~
cc1: all warnings being treated as errors
go tool dist: FAILED: gcc -Wall -Wstrict-prototypes -Wextra -Wunused -Wno-sign-compare -Wno-missing-braces -Wno-parentheses -Wno-unknown-pragmas -Wno-switch -Wno-comment -Wno-missing-field-initializers -Werror -fno-common -ggdb -pipe -Wuninitialized -O2 -fmessage-length=0 -c -m64 -I /home/test/.local/gvm/gos/go1.4/include -DPLAN9PORT -I /home/test/.local/gvm/gos/go1.4/src/lib9 -o $WORK/fltfmt.o /home/test/.local/gvm/gos/go1.4/src/lib9/fmt/fltfmt.c
```

**Comment by BenKnigge** [comment]
I'm going to close this issue. 

Moving forward I'm planning on implementing binary as the default installation method unless I hear a good argument against doing so.
