### ISSUE TITLE
Does GVM is maintained?

### ISSUE THREAD

**Issue by x2es** [moovweb/gvm#213]

**Comment by markeissler** [comment]
I'd like to know this too. I'm preparing a pretty big update referenced in #219. I noticed there's a huge backlog of issues. I'd be happy to take over this project if the owner wants to ping me.

**Comment by brendensoares** [comment]
uh oh, no response...maintaining an open source project like this is no easy task :/

**Comment by markeissler** [comment]
Since it doesn't appear to be a maintained project... I created [GVM2](https://github.com/markeissler/gvm2)!

**Comment by BenKnigge** [comment]
Hello, I've recently taken over as maintainer of this project. If you have any features that you would be willing to merge back into gvm your pull requests would be appreciate.
