### ISSUE TITLE
Automatically `gvm use`... on per-directory .go-version files

### ISSUE THREAD

**Issue by mcandre** [moovweb/gvm#219]
chruby and ndenv help Ruby and Node.js programmers by automatically the right version of a programming language based on per-directory files like .ruby-version and .node-version. Could gvm do the same with .go-version files?

**Comment by valerius** [comment]
+1  (though such a request has already been rejected. https://github.com/sdkman/sdkman-cli/issues/219 )

**Comment by jbussdieker** [comment]
+1

**Comment by markeissler** [comment]
As a devoted rvm user, I'd like to suggest support for both .go-version and .go-pkgset (akin to .ruby-version and .ruby-gemset) files. The implementation would be similar to rvm in that when you change to a directory that features these files both `gvm use` and `gvm pkgset` would be called with the contents of each respective file as arguments.

Another neat thing in the rvm implementation is that changing out of a directory causes rvm to look for the next governing .ruby-version/.ruby-gemset files in parent directories.

I just started using gvm today but could look into adding this functionality.

**Comment by mcandre** [comment]
> support for both .go-version

+1000

**Comment by markeissler** [comment]
Just as a heads up to everyone, I've been working on implementing the following:

- support for __.go-version__ in current directory or parent
- support for __.go-pkgset__ in current directory or parent

The above files will be read and parsed on every execution of cd. If one of the above files doesn't appear in the current directory (normally the project directory), then parent directories will be searched and the first encountered __.go-version__ and __.go-pkgset__ file will be applied. By *applied* I mean that the `go use <version>` and `go use pkgset <pkgname>` commands will be executed.

This described behavior is similar to the way rvm works, and for those of us that work with both `rvm` and `gvm` this begs the question: will rvm continue to function correctly? In short: yes.

Content for these plain text files is simply the name of the Go version as it appears in `gvm list` output (for .go-version) and the name of the pkgset as it appears in `gvm pkgset list`.

I'm still working out the details as to what the fallback status is when the contents of either file are incorrect (e.g. falling back to __default__ or __system__ or __global__ only works if those targets exist!).

Before everyone gets too giddy about the `rvm` support, let me point out that there is still a problem with having both `rvm` and `gvm` co-exist with regard to the former insisting that its directories appear first in PATH. I'm already on a fix for this and it can be tracked here:

#225 [Both rvm and gvm can't coexist happily](https://github.com/moovweb/gvm/issues/225)

I'm hoping that both __.go-version__ and __.go-pkgset__ become as well-used with Go as the similar __.ruby-version__ and __.ruby-gemset__ are for Ruby development.

**Comment by markeissler** [comment]
I'm happy to announce that I have a branch available for testing that implements both __.go-version__ and __.go-pkgset__ and supports the functionality mentioned in my previous comment above.

In addition, I've implemented a fix that allows `gvm` to work alongside `rvm`.

I've updated some of the `README.md` to reflect the new functionality. Although I've tested this extensively along the way in a VM, it's only now that I"ve installed it on my dev machine for regular use. So, what I need now is broader testing.

That brings us to: __How do you install this?__

Unless I'm mistaken, it doesn't look like there's any builtin way to update a `gvm` install at the moment. I'll get on that soon enough. But in the meantime, the steps I used are below __(BE SURE TO BACKUP YOUR $HOME/.gvm DIRECTORY FIRST!)__.

```
Step 1 - grab the tagged commit from my branch (this creates just the .git directory)
---
git clone -b go-version-pkgset-pre1 --no-checkout "https://github.com/markeissler/gvm.git" ~/.gvm/gvm-update.tmp

Step 2 - move the resulting .git directory in place, then reset the local repo state
---
mv ~/.gvm/gvm-update.tmp/.git ~/.gvm/
rmdir ~/.gvm/gvm-update.tmp/
builtin cd ~/.gvm
git reset --hard HEAD
mv git.bak git.bak.old
mv .git git.bak

Step 3 - open a new terminal to test

```

Proceed with caution at Step 3. In the odd case that you need to disable `rvm` by preventing it to load at session startup (by commenting out the source lines in your .bashrc, etc) you will want to be able to do that from a functioning terminal (the one you used to upgrade the install).

With that said, this is a pretty nice enhancement.

**Comment by markeissler** [comment]
These updates have been working great for me. Still need to test with zsh (which I don't use).

**Comment by mcandre** [comment]
Yay, glad to see this super helpful feature being tested now!

I wonder if it's possible to port this to posh-gvm for Windows (PowerShell) users https://github.com/flofreud/posh-gvm

**Comment by markeissler** [comment]
Just completed a whole bunch of refactor and this update now supports **zsh** as well.

I've been using the previous tag with bash for the past several weeks without any problems. It's been awesome. Don't know how Go folks get by without this functionality.

Follow the directions outlined in my previous comment but use the following input for **Step 1** as the tag has been updated:

```
git clone -b go-version-pkgset-pre2 --no-checkout "https://github.com/markeissler/gvm.git" ~/.gvm/gvm-update.tmp
```

I hope to update the installer in the future so that updates are easy.

**Comment by ghostsquad** [comment]
Any update one when this will be released?

**Comment by markeissler** [comment]
Sadly, no. PR #233 has been passing travis tests since sometime in January. @jbussdieker (project maintainer) has been MIA and mostly disengaged with the project it seems (based on the number of unresolved/unacknowledged issues). I have also volunteered for a transfer of ownership to take over the project.

**I may end up forking** since I put a ton of work into this but have been reluctant to do so (so far) because of the issue backlog that would just disappear. That is, I would create a new repo with a new name (like gvm2) to avoid confusion with the abandoned project. Not sure what to do, but won't add more improvements until the stalemate is resolved.

**Comment by nathantsoi** [comment]
did you fork @markeissler ? should we switch to gvm2?

**Comment by markeissler** [comment]
Hi @nathantsoi. Thanks for your interest. I have not yet forked but will do so this week, likely creating a divorced fork for gvm2. I think that will provide more clarity to the community rather than continue along as yet another fork of gvm. I will open up issues there when I do that and post back to here when done.

**Comment by nathantsoi** [comment]
:+1:

**Comment by markeissler** [comment]
@nathantsoi @ghostsquad @jbussdieker [GVM2](https://github.com/markeissler/gvm2) is now available in its first release and supports the `.go-version` and `.go-pkgset` files mentioned previously.

**Comment by markohaapala** [comment]
For local gvm and nvm) I've made a hacky way of doing this automatically when entering a directory. Got the idea [here](https://stackoverflow.com/questions/3360738/execute-a-bash-function-upon-entering-a-directory/3360812#3360812).

.zshrc:
`
# automatically switch to local node/go version
checkRc() {
  if [ "$PWD" != "$MYOLDPWD"  ]; then
    MYOLDPWD="$PWD";
    if [ -f .nvmrc  ]; then
      nvm use
    fi
    if [ -f .gvmrc  ]; then
      gvm use $(cat .gvmrc)
    fi
  fi
}
export PROMPT_COMMAND=checkRc
precmd() { eval "$PROMPT_COMMAND"  }
`
Example:
`
marko at x270 in ~
$ cd src/cryptostatus
Now using version go1.8.3
`

**Comment by BenKnigge** [comment]
I plan on implementing a command to use the version defined in go mod at some point in the near future.

**Comment by michaelfranzl** [comment]
> I plan on implementing a command to use the version defined in go mod at some point in the near future.

@BenKnigge is this already implemented?

**Comment by ghostsquad** [comment]
I've switched to using ASDF exclusively. Works really well.

**Comment by sivunestori** [comment]
My derived hack has been working since -17. Just saying.
