### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by mcandre** [moovweb/gvm#220]
Does gvm support traditional Windows environments (PowerShell or Command Prompt)? I could work around some Windows issues by using Git Bash, but for I would appreciate if gvm supported non-bash environments.

If not, does anyone know of a Windows equivalent of gvm?

**Comment by marcus-crane** [comment]
Check out https://github.com/danielkermode/gvm

**Comment by mcandre** [comment]
Works on my machine!
