### ISSUE TITLE
Both rvm and gvm can't coexist happily

### ISSUE THREAD

**Issue by markeissler** [moovweb/gvm#225]
The Ruby Version Manager (rvm) is anti-social when it comes to rewriting the PATH or overriding the shell cd() function.

I'm working on a couple of fixes to gvm that will allow it to coexist happily with rvm. The first part involves the ability to preserve rvm's cd() override when implementing the same for gvm as part of my patch relating to:
#219 -- [Automatically `gvm use`... on per-directory .go-version files](https://github.com/moovweb/gvm/issues/219)

The second part involves introducing dynamic PATH generation, which will replace static PATH definitions currently located in each of the environments files. Because this feature can update dynamically, user changes to the PATH at anytime will be realized automatically (or at least after issuing a new `gvm use` command). As well, existing PATH will be parsed and munged to create a new PATH where `rvm` elements appear first (required by rvm) and `gvm` elements will appear second, followed by all other elements.

I should have a feature branch implementing this fix available over the next few days.

**Comment by mcandre** [comment]
+1000

**Comment by markeissler** [comment]
This functionality is now available for testing. See my updated comments for #219.

Specifically [my announcement comment](https://github.com/moovweb/gvm/issues/219#issuecomment-249750756).

These changes are on a separate branch on my fork right now. Soon as I feel the code is stable I'll open a PR.

**Comment by markeissler** [comment]
[GVM2](https://github.com/markeissler/gvm2) is now in its first release.

Closing this comment as my work is now in the new project.
