### ISSUE TITLE
Feature Request - gvm current 

### ISSUE THREAD

**Issue by cescoferraro** [moovweb/gvm#226]
The analog repo for NodeJS has a convinient command to get the current version .
https://github.com/creationix/nvm
### Expected behaviour

```
$ gvm current
go 1.7
```

**Comment by markeissler** [comment]
What does "current" refer to? The most-current stable release available or the current version you are using? Because the latter can be found with `gvm list`:

```sh
$ gvm list

gvm gos (installed)

=> go1.6.3
   go1.7
   go1.7.1
   system
```

And the one indicated with "=>" is the current version being used.

**Comment by markeissler** [comment]
Or at least that's how it works with [GVM2](https://github.com/markeissler/gvm2)!

**Comment by nikhiljindal** [comment]
+1 to the original FR.

Have been trying to figure out how to view the current go version I am using and never thought of running gvm list to get it :)
Thanks @markeissler for posting it!

**Comment by BenKnigge** [comment]
There are multiple similar tickets making this request. It's on my todo list.

**Comment by BenKnigge** [comment]
duplicate issue https://github.com/moovweb/gvm/issues/145
