### ISSUE TITLE
"gvm install tip" doesn't find tip

### ISSUE THREAD

**Issue by vielmetti** [moovweb/gvm#231]
The documentation in README reads

> Install/Uninstall Go versions with gvm install [tag] where tag is "60.3", "go1", "weekly.2011-11-08", or "tip"

but when I run

```
emv@armv8hello:~$ gvm version; gvm install tip
Go Version Manager v1.0.22 installed at /home/emv/.gvm
Updating Go source...
ERROR: Unrecognized Go version
```

System is Ubuntu 16.04 on a multicore ARMv8 system.

**Comment by WillSewell** [comment]
Duplicate of https://github.com/moovweb/gvm/issues/125

**Comment by vielmetti** [comment]
Closing in favor of #125. "gvm install master" did work. I suggest changing the documentation
