### ISSUE TITLE
Add mirror repo support via environment variable.

### ISSUE THREAD

**Issue by abcfy2** [moovweb/gvm#237]
Just like the [nvm](https://github.com/creationix/nvm), the nodejs version manager, which is support download from mirror repo by setting a environment variable `NVM_NODEJS_ORG_MIRROR`.

Because China has blocked google totally, so gvm cannot access to any google websites.

```
$ gvm install go
Downloading Go source...
ERROR: Couldn't download Go source. Check the logs /home/fengyu/.gvm/logs/go-download.log

fatal: unable to access 'https://go.googlesource.com/go/': Failed to connect to go.googlesource.com port 443: 
```

**Comment by abcfy2** [comment]
#238 can set go source repo to another mirror. I'm finding the way to set go binary mirror.

**Comment by BenKnigge** [comment]
The environment variable GO_BINARY_BASE_URL was created with the following commit. 

https://github.com/moovweb/gvm/commit/ed2c95bcafaa91c123ec3868570d07b8d6e8186c
