### ISSUE TITLE
Feature Request - Install from source (master branch)

### ISSUE THREAD

**Issue by fubarhouse** [moovweb/gvm#244]
I'd like to see GVM be able to install from the master source repository from googlecode/github.
I believe others using GVM would have an interest in this feature, but feel free to decline.

**Comment by fubarhouse** [comment]
So apparently this actually works:
`gvm install master --source=master`

So I'll close this one off, my apologies.

**Comment by maroux** [comment]
Evidently this doesn't work any more?

```
→ gvm listall | grep master
<no result>
```
