### ISSUE TITLE
installing gvm fails to update PATH variable in my .profile

### ISSUE THREAD

**Issue by chrisvelevitch** [moovweb/gvm#268]
On OSX 10.11.6, I tried each of the following:-

* `bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)`
* `curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer | bash`
* `zsh < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)`
* `curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer | zsh`

and in each case, the PATH variable is NOT updated. I ended up having to manually update the PATH variable.

And then, I can't use the `use` command, I get:-

`ERROR: Unrecognized command line argument: 'use'`

**Comment by chrisvelevitch** [comment]
It turns out that the scripts don't handle aliases of commands used in any of the scripts.

**Comment by alexcurtin** [comment]
@chrisvelevitch How did you fix the Unrecognized command line argument: 'use' issue?

**Comment by chrisvelevitch** [comment]
@alexcurtin I removed/renamed the offending aliases on my machine, removed and reinstalled `gvm`.
