### ISSUE TITLE
go1.8.* can't be install by gvm

### ISSUE THREAD

**Issue by opendb2** [moovweb/gvm#279]
cat /home/ec2-user/.gvm/logs/go-go1.8.3-compile.log
##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using /home/ec2-user/.gvm/gos/go1.4.
bootstrap/cmd/internal/dwarf
bootstrap/cmd/internal/sys
bootstrap/cmd/internal/obj
bootstrap/cmd/internal/obj/arm
bootstrap/cmd/internal/obj/arm64
bootstrap/cmd/internal/obj/mips
bootstrap/cmd/internal/obj/ppc64
bootstrap/cmd/internal/obj/s390x
bootstrap/cmd/internal/obj/x86
bootstrap/cmd/asm/internal/arch
bootstrap/cmd/asm/internal/flags
bootstrap/cmd/asm/internal/lex
bootstrap/cmd/asm/internal/asm
bootstrap/cmd/internal/bio
bootstrap/cmd/asm
bootstrap/cmd/compile/internal/ssa
go build bootstrap/cmd/compile/internal/ssa: /home/ec2-user/.gvm/gos/go1.4/pkg/tool/linux_amd64/6g: signal: killed
bootstrap/cmd/compile/internal/syntax
bootstrap/cmd/internal/gcprog
bootstrap/math/big
bootstrap/debug/pe
bootstrap/cmd/link/internal/ld
bootstrap/cmd/link/internal/amd64
bootstrap/cmd/link/internal/arm
bootstrap/cmd/link/internal/arm64
bootstrap/cmd/link/internal/mips
bootstrap/cmd/link/internal/mips64
bootstrap/cmd/link/internal/ppc64
bootstrap/cmd/link/internal/s390x
bootstrap/cmd/link/internal/x86
bootstrap/cmd/link
go tool dist: FAILED: /home/ec2-user/.gvm/gos/go1.4/bin/go install -gcflags=-l -tags=math_big_pure_go -v bootstrap/cmd/...: exit status 1

**Comment by opendb2** [comment]
from go1.4-1.7 and go1.9 can be installed except go1.8*

**Comment by mandarvaze** [comment]
At first I got an error because some directory in `$TMPDIR` did not exist. So I had created it, and then, I get *similar* error, except I get exit status **2**, not 1

```shell
##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using /Users/mandar/.gvm/gos/go1.4.
failed MSpanList_Insert 0x129b820 0x1b97352de4ade 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.MSpanList_Insert(0x827c60, 0x129b820)
	/usr/local/go/src/runtime/mheap.c:692 +0x8f
runtime.MHeap_Alloc(0x827b20, 0x1, 0x10000000005, 0x977a9)
	/usr/local/go/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0x82e9f8, 0x8b3458)
	/usr/local/go/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0x1297000, 0x5, 0x1680760)
	/usr/local/go/src/runtime/mcache.c:90 +0xa0

goroutine 1 [running, locked to thread]:
runtime.switchtoM()
	/usr/local/go/src/runtime/asm_amd64.s:198 fp=0xc20801d4c8 sp=0xc20801d4c0
runtime.deferproc(0x8, 0x6a2a18)
	/usr/local/go/src/runtime/panic.go:78 +0xb7 fp=0xc20801d4f0 sp=0xc20801d4c8
sync.(*Once).Do(0x8207f8, 0x6a2a58)
	/usr/local/go/src/sync/once.go:41 +0x9b fp=0xc20801d518 sp=0xc20801d4f0
syscall.Getenv(0x5c70b0, 0x8, 0x0, 0x0, 0x98c00)
	/usr/local/go/src/syscall/env_unix.go:72 +0x84 fp=0xc20801d588 sp=0xc20801d518
time.init()
	/usr/local/go/src/time/zoneinfo.go:257 +0x409 fp=0xc20801d5e8 sp=0xc20801d588
os.init()
	/usr/local/go/src/os/types_notwin.go:25 +0x97 fp=0xc20801d640 sp=0xc20801d5e8
path/filepath.init()
	/usr/local/go/src/path/filepath/symlink_unix.go:7 +0x9c fp=0xc20801d678 sp=0xc20801d640
go/scanner.init()
	/usr/local/go/src/go/scanner/scanner.go:760 +0x97 fp=0xc20801d688 sp=0xc20801d678
go/parser.init()
	/usr/local/go/src/go/parser/parser.go:2462 +0x97 fp=0xc20801d6a8 sp=0xc20801d688
main.init()
	/usr/local/go/src/cmd/go/zdefaultcc.go:6 +0x9b fp=0xc20801d798 sp=0xc20801d6a8
runtime.main()
	/usr/local/go/src/runtime/proc.go:58 +0xe4 fp=0xc20801d7e0 sp=0xc20801d798
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801d7e8 sp=0xc20801d7e0

goroutine 2 [runnable]:
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:90
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/usr/local/go/src/runtime/mgc0.go:82
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
go tool dist: FAILED: /Users/mandar/.gvm/gos/go1.4/bin/go install -gcflags=-l -tags=math_big_pure_go -v bootstrap/cmd/...: exit status 2
```

**Comment by mandarvaze** [comment]
I also tried `go1.9` (not `.2`) I get similar error.

**fatal error: MSpanList_Insert** seems to be the base error.

with 1.9, the last error is
```
go tool dist: FAILED: /Users/mandar/.gvm/gos/go1.9/pkg/tool/darwin_amd64/asm -I /var/folders/3z/3363nmvj1p7gnrn657lt71xr0000gn/T/go-tool-dist-454068759/runtime -I /Users/mandar/.gvm/gos/go1.9/pkg/include -D GOOS_darwin -D GOARCH_amd64 -D GOOS_GOARCH_darwin_amd64 -o /var/folders/3z/3363nmvj1p7gnrn657lt71xr0000gn/T/go-tool-dist-454068759/runtime/sys_darwin_amd64.o /Users/mandar/.gvm/gos/go1.9/src/runtime/sys_darwin_amd64.s: exit status 2
```

**Comment by iptq** [comment]
that signal killed sounds like an out of memory thing

**Comment by BenKnigge** [comment]
It's been several years since the last activity on this issue. I will likely close it in the near future unless someone is still having this issue.
