### ISSUE TITLE
How do I uninstall gvm?

### ISSUE THREAD

**Issue by doapp-ryanp** [moovweb/gvm#285]
How do you remove gvm from a macOS system? I'm not a fan of how gvm manipulates `$GOPATH` (https://github.com/moovweb/gvm/issues/189) so I would like to cleanly remove gvm.

Are these steps sufficient?
1.  `rm -rf ~/.gvm`
1.  Remove the following line in `~/.bash_profile`: `[[ -s "/Users/ryan/.gvm/scripts/gvm" ]] && source "/Users/ryan/.gvm/scripts/gvm"`

**Comment by e-nikolov** [comment]
Did you try `gvm implode`? That's what the Readme suggests.

Also I have a [fork](https://github.com/e-nikolov/gvm) with the GOPATH manipulations removed, which works for me, but I haven't tested it on mac.

**Comment by doapp-ryanp** [comment]
Thanks. I swear I grep'd the readme... guess not. closing.

**Comment by curiouscod3** [comment]
CANNOT UNINSTALL on macOS; Please fix this for mac users please

$gvm implode         
gvm_implode:read:1: -p: no coprocess

Action cancelled

**Comment by curiouscod3** [comment]
I cannot uninstall gvm;  

**$gvm implode**         
gvm_implode:read:1: -p: no coprocess

Action cancelled

**Comment by funkyshu** [comment]
Answer to old question about "no coprocess", looks like the `read -p "some prompt test"` behavior in bash is not the same in zsh.  In zsh, you `echo` or `printf` for a prompt, then call `read`.  `-p` in zsh's `read` means read from coprocess.  
Either way, the the calling code:
```
gvm_implode () {
	read -p "Are you sure? [y/N] " -n 1 -r
	echo
	if [[ ! $REPLY =~ ^[Yy]$ ]]
	then
		display_message "Action cancelled"
	else
		(
			rm -rf "$GVM_ROOT" && display_message "GVM successfully removed"
		) || display_error "Failed to uninstall gvm"
	fi
}
```
ultimately just does `rm -rf "$GVM_ROOT"`.

**Comment by jcollum** [comment]
I tried it in bash and got about a million " Directory not empty" errors. 

```
$ gvm implode
Are you sure? [y/N] y

rm: /Users/justin.collum/.gvm/pkgsets/go1.14/global/pkg/mod/gotest.tools@v2.2.0+incompatible/Gopkg.toml: Permission denied
rm: /Users/justin.collum/.gvm/pkgsets/go1.14/global/pkg/mod/gotest.tools@v2.2.0+incompatible/.codecov.yml: Permission denied
rm: /Users/justin.collum/.gvm/pkgsets/go1.14/global/pkg/mod/gotest.tools@v2.2.0+incompatible/LICENSE: Permission denied
```

looks like a bug to me.

**Comment by doggy8088** [comment]
Here is what I tried. And it works!

```sh
chmod u+w -R ~/.gvm/
gvm implode
```

**Comment by Ivlyth** [comment]
> Or simple
> 
> ```
> sudo rm -rf /Users/xxx/.gvm
> ```

and additionally remove the source script inside .bashrc OR .zshrc OR others ?

**Comment by jm-nab** [comment]
If your terminal still has the env vars and functions set, you might be able to clear them out
 
```
# backup your old env just in case
set > old.env

# wipe everything in the ENV and rm .gvm dir
for item in $(set | grep -i __gvm | grep '()' | awk '{ print $1 }');do 
    unset -f $item
done
unset -f _
unset -f cd
unset GVM_ROOT
unset GVM_PATH_BACKUP
unset GVM_VERSION
rm -rf ~/.gvm
```

**Comment by adamc55** [comment]
Having just experienced this... not a good way to run an uninstall.

**Comment by victorolaiya** [comment]
> Here is what I tried. And it works!
> 
> ```shell
> chmod u+w -R ~/.gvm/
> gvm implode
> ```

Works like a charm!
