### ISSUE TITLE
gvm install go1.4 fails on macOS 10.13.2

### ISSUE THREAD

**Issue by wujunze** [moovweb/gvm#287]
When I try to install Go 1.4 via gvm, I get a compile error.
### Trace
```
wujunze@wujunzedeMacBook-Pro: ~
 $ CGO_ENABLED=0 gvm install go1.4                                                                                               [10:33:50]
Installing go1.4...
 * Compiling...



ERROR: Failed to compile. Check the logs at /Users/wujunze/.gvm/logs/go-go1.4-compile.log
ERROR: Failed to use installed version
FAIL

wujunze@wujunzedeMacBook-Pro: ~
 $                                                                                                                               [10:35:14]
FAIL

wujunze@wujunzedeMacBook-Pro: ~
 $ cat /Users/wujunze/.gvm/logs/go-go1.4-compile.log                                                                             [10:35:14]
# Building C bootstrap tool.
cmd/dist

# Building compilers and Go bootstrap tool for host, darwin/amd64.
lib9
libbio
liblink
cmd/cc
cmd/gc
cmd/6l
/Users/wujunze/.gvm/gos/go1.4/src/cmd/6l/../ld/dwarf.c:1472:15: error: implicit conversion from 'int' to 'char' changes value from 156 to -100 [-Werror,-Wconstant-conversion]
/Users/wujunze/.gvm/gos/go1.4/src/cmd/6l/../ld/dwarf.c:1756:21: error: implicit conversion from 'int' to 'char' changes value from 144 to -112 [-Werror,-Wconstant-conversion]
/Users/wujunze/.gvm/gos/go1.4/src/cmd/6l/../ld/lib.h:168:13: note: expanded from macro 'cput'
go tool dist: FAILED: clang -Wall -Wstrict-prototypes -Wextra -Wunused -Wno-sign-compare -Wno-missing-braces -Wno-parentheses -Wno-unknown-pragmas -Wno-switch -Wno-comment -Wno-missing-field-initializers -Werror -fno-common -ggdb -pipe -Wuninitialized -O2 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -mmacosx-version-min=10.6 -c -m64 -I /Users/wujunze/.gvm/gos/go1.4/include -I /Users/wujunze/.gvm/gos/go1.4/src/cmd/6l -o /Users/wujunze/.gvm/gos/go1.4/pkg/obj/cmd/6l/dwarf.o /Users/wujunze/.gvm/gos/go1.4/src/cmd/6l/../ld/dwarf.c
```
### System
```
wujunze@wujunzedeMacBook-Pro: ~
 $ gvm version                                                                                                                               [10:38:39]
Go Version Manager v1.0.22 installed at /Users/wujunze/.gvm

wujunze@wujunzedeMacBook-Pro: ~
 $ clang --version                                                                                                                           [10:38:45]
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

wujunze@wujunzedeMacBook-Pro: ~
 $ go version                                                                                                                                [10:39:03]
go version go1.7.4 darwin/amd64

wujunze@wujunzedeMacBook-Pro: ~
 $ system_profiler SPSoftwareDataType | grep 'System Version'                                                                                [10:39:07]
      System Version: macOS 10.13.2 (17C205)
```
### Workaround
```
CGO_ENABLED=0 gvm install go1.4
```

**Comment by ibunubi** [comment]
add `--binary` on tail

**Comment by xnathanh** [comment]
add --binary on tail

not work for me.

`$ gvm install go1.4 --binary     
Installing go1.4 from binary source

 12:00:10  ~  🐍 3.6.5 
$ gvm use go1.4                  
Now using version go1.4

 12:00:14  ~  🐍 3.6.5 
$ export GOROOT_BOOTSTRAP=$GOROOT

 12:00:17  ~  🐍 3.6.5 
$ go
failed MSpanList_Insert 0x1704000 0x117b88681917 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x7ffa6b)
	/usr/local/go/src/runtime/panic.go:491 +0xad fp=0x7ffeefbfea50 sp=0x7ffeefbfea20
runtime.MSpanList_Insert(0x82af28, 0x1704000)
	/usr/local/go/src/runtime/mheap.c:692 +0x8f fp=0x7ffeefbfea78 sp=0x7ffeefbfea50
MHeap_FreeSpanLocked(0x827b20, 0x1704000, 0x100)
	/usr/local/go/src/runtime/mheap.c:583 +0x163 fp=0x7ffeefbfeab8 sp=0x7ffeefbfea78
MHeap_Grow(0x827b20, 0x8, 0x0)
	/usr/local/go/src/runtime/mheap.c:420 +0x1a8 fp=0x7ffeefbfeaf8 sp=0x7ffeefbfeab8
MHeap_AllocSpanLocked(0x827b20, 0x1, 0x122e080)
	/usr/local/go/src/runtime/mheap.c:298 +0x365 fp=0x7ffeefbfeb38 sp=0x7ffeefbfeaf8
mheap_alloc(0x827b20, 0x1, 0x7f0000000012, 0x7fff5fe4c3bf)
	/usr/local/go/src/runtime/mheap.c:190 +0x121 fp=0x7ffeefbfeb60 sp=0x7ffeefbfeb38
runtime.MHeap_Alloc(0x827b20, 0x1, 0x10000000012, 0x977a9)
	/usr/local/go/src/runtime/mheap.c:240 +0x66 fp=0x7ffeefbfeb98 sp=0x7ffeefbfeb60
MCentral_Grow(0x82f898, 0x1238200)
	/usr/local/go/src/runtime/mcentral.c:197 +0x8b fp=0x7ffeefbfec00 sp=0x7ffeefbfeb98
runtime.MCentral_CacheSpan(0x82f898, 0x7ffeefbfec70)
	/usr/local/go/src/runtime/mcentral.c:85 +0x167 fp=0x7ffeefbfec38 sp=0x7ffeefbfec00
runtime.MCache_Refill(0x1700000, 0x12, 0x7ffeefbfec90)
	/usr/local/go/src/runtime/mcache.c:90 +0xa0 fp=0x7ffeefbfec60 sp=0x7ffeefbfec38
runtime.mcacheRefill_m()
	/usr/local/go/src/runtime/malloc.c:368 +0x57 fp=0x7ffeefbfec80 sp=0x7ffeefbfec60
runtime.onM(0x6a2870)
	/usr/local/go/src/runtime/asm_amd64.s:273 +0x9a fp=0x7ffeefbfec88 sp=0x7ffeefbfec80
runtime.mallocgc(0x120, 0x590240, 0x0, 0x0)
	/usr/local/go/src/runtime/malloc.go:178 +0x85b fp=0x7ffeefbfed38 sp=0x7ffeefbfec88
runtime.newobject(0x590240, 0x1700000)
	/usr/local/go/src/runtime/malloc.go:353 +0x49 fp=0x7ffeefbfed60 sp=0x7ffeefbfed38
runtime.newG(0xb17fa)
	/usr/local/go/src/runtime/proc.go:233 +0x2a fp=0x7ffeefbfed78 sp=0x7ffeefbfed60
allocg(0x817ac0)
	/usr/local/go/src/runtime/proc.c:925 +0x1f fp=0x7ffeefbfed88 sp=0x7ffeefbfed78
runtime.malg(0x8000, 0x817e40)
	/usr/local/go/src/runtime/proc.c:2106 +0x1f fp=0x7ffeefbfedb8 sp=0x7ffeefbfed88
runtime.mpreinit(0x818680)
	/usr/local/go/src/runtime/os_darwin.c:137 +0x27 fp=0x7ffeefbfedd0 sp=0x7ffeefbfedb8
mcommoninit(0x818680)
	/usr/local/go/src/runtime/proc.c:201 +0xc9 fp=0x7ffeefbfedf8 sp=0x7ffeefbfedd0
runtime.schedinit()
	/usr/local/go/src/runtime/proc.c:138 +0x6e fp=0x7ffeefbfee20 sp=0x7ffeefbfedf8
runtime.rt0_go(0x7ffeefbfee50, 0x1, 0x7ffeefbfee50, 0x0, 0x1, 0x7ffeefbff050, 0x0, 0x7ffeefbff053, 0x1303350, 0x7ffeefbff09a, ...)
	/usr/local/go/src/runtime/asm_amd64.s:95 +0x116 fp=0x7ffeefbfee28 sp=0x7ffeefbfee20`

**Comment by qw4n7y** [comment]
and why did you close the issue?

**Comment by haysclark** [comment]
Dup of #281
