### ISSUE TITLE
THANK YOU!

### ISSUE THREAD

**Issue by sebito91** [moovweb/gvm#289]
No issues here, just wanted to thank you for pulling this tool together. I rely quite heavily on this tool for my development environment and just wanted to give a quick shout out to the maintainers!

👍 🎉 🎈

**Comment by tbfh777** [comment]
I'd been trying to put off wading in to go/snapd, et.al, but ubuntu related issues forced me in. Getting these complex tools working together on multiple platforms could have been an unending nightmare. Thanks to this, 'Swiss Army Knife', and some very useful tutorials, I was able to get a usable framework in place in 2 days. Thanks so much.
