### ISSUE TITLE
No command 'gvm' found, did you mean:

### ISSUE THREAD

**Issue by wan9wu** [moovweb/gvm#291]
```
$ bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
ERROR: Already installed!
```
```
$ gvm
No command 'gvm' found, did you mean:
```
WHY?

**Comment by HaraldNordgren** [comment]
Could hopefully be mitigated by https://github.com/moovweb/gvm/pull/292

I had a stale installation lying around in `~/.gvm`, maybe it's the same for you.

**Comment by n0b0dyvn** [comment]
Maybe because you use another shell like zsh instead of bash. So when gvm install rewrite .<shell>rc, it wrote to .bashrc instead of your shell init file.

**Comment by wcchh** [comment]
Close current terminal and open another one might help.

**Comment by voxxit** [comment]
@wan9wu Once your run that command, you should source the newly-created bash script into your terminal:

```shell
source ~/.gvm/scripts/gvm
```

Or, as @wcchh mentioned, just re-open your terminal window.

**Comment by besteffects** [comment]
> Close current terminal and open another one might help.

Your reply worked for me. Interesting why...

**Comment by shivkumarsingh7** [comment]
Tried everything still its not working.
**/Users/shivam/.gvm/scripts/gvm-default:unset:1: GOROOT^M: invalid parameter name**

**Comment by madhavdutta** [comment]
Use 

zsh < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
ERROR: Already installed!

Instead of 

bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
ERROR: Already installed!

**Comment by 4tg0x** [comment]
> Use
> 
> zsh < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
> 
> Instead of
> 
> bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)

thank you a ton, like 1000000 times..

**Comment by RicHincapie** [comment]
Hey, I have
`[[ -s "/home/ric/.gvm/scripts/gvm" ]] && source "/home/ric/.gvm/scripts/gvm"` in my .zshrc
but
```
❯ ls .gvm/scripts/ | grep gvm
gvm-check
gvm-default
gvm.in

```
So nothing's sourced. Any idea?
