### ISSUE TITLE
Feature request: Keywords to install latest stable, development version

### ISSUE THREAD

**Issue by squash** [moovweb/gvm#301]
Seeming a common usage is gvm listall, scan the list to find the newest stable version, and gvm install [version]. It would be nice if you could use a keyword "stable" to automatically determine the newest stable release, and "development" to install the newest unstable release.

Mentioned in #145 however that ticket has received no love in 3 years.

**Comment by BenKnigge** [comment]
I've recently taken over as the maintainer of this project and this is a feature that I plan on implementing in the near future.

**Comment by BenKnigge** [comment]
I'm going to close this issue and address the original request.
