### ISSUE TITLE
gvm install fails with "go: command not found" on Ubuntu 18.04

### ISSUE THREAD

**Issue by cirosantilli** [moovweb/gvm#302]
At 6ecd46d8b58c18f2a7bd5a1ab604cb57443cd35c:

```
$ bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
$ gvm install go1.11
Downloading Go source...
Installing go1.11...
 * Compiling...
/home/ciro/.gvm/scripts/install: line 84: go: command not found
ERROR: Failed to compile. Check the logs at /home/ciro/.gvm/logs/go-go1.11-compile.log
ERROR: Failed to use installed version
```

Installing Go with package manager solved it:

```
sudo apt-get install golang-go
```

but feels a bit bad to need go to install go. At least document the dep at: https://github.com/moovweb/gvm/tree/6ecd46d8b58c18f2a7bd5a1ab604cb57443cd35c#debianubuntu

**Comment by jswh** [comment]
What about add an option to download compiled binary rather than compile from source.

**Comment by reddyvinod** [comment]
Please refer to [README.md](https://github.com/moovweb/gvm#a-note-on-compiling-go-15) on how to install go versions 1.5+.

**Comment by JacobDB** [comment]
@reddyvinod I'm getting this even when trying to install 1.4

**Comment by Monarch73** [comment]
yet another bug in regards to this:
gvm install -B fails on arm cpus. It obviously installs x86 version of the binary....

**Comment by BenKnigge** [comment]
@Monarch73  could you create a separate issue regarding arm support.

**Comment by BenKnigge** [comment]
@Monarch73  I've merged a pr for arm64

**Comment by Kungitoo** [comment]
Could you add a link to a readme if someone tries to install go 1.5+ without having already go installed?

**Comment by eisukeesaki** [comment]
same issue. worked around it by `brew install go`, `gvm install go1.9` `gvm use go1.9` `brew uninstall go`

**Comment by vansonhkoct** [comment]
same issue

**Comment by adzimzf** [comment]
I face the same problem and solved by following [this](https://github.com/moovweb/gvm/issues/302#issuecomment-1434322062) steps

thanks @eisukeesaki

**Comment by rios0rios0** [comment]
Are you guys going to address this issue to install without Go already installed?
