### ISSUE TITLE
gvm seems to require some version of go already installed

### ISSUE THREAD

**Issue by bjm88** [moovweb/gvm#309]
I have a new Amazon Linux (CentOS/RH) machine, followed install instructions exactly as on readme and it failed looking for go to actually install go?!?  Tried

gvm install go1.11.1 and it failed.

I then did sudo yum install go to get some version (1.9 is what it gave)
then gvm worked as expected to get and set other versions.  Very weird, shouldn't need go to install go....

**Comment by vimishor** [comment]
Installing from binary should work:

``` bash
$ gvm install go1.11.1 -B
```
