### ISSUE TITLE
Potential gvm integration problem with vscode?

### ISSUE THREAD

**Issue by zhiqiangxu** [moovweb/gvm#341]
I installed `go1.13` via:

```gvm install go1.13 -B```

I've installed 3 versions in total:

```
$ gvm list

gvm gos (installed)

   go1.10
   go1.12
=> go1.13
```

Then I changed the `gopath` and `goroot` in settings.json:
```

  "go.gopath": "/Users/xuzhiqiang/.gvm/pkgsets/go1.13/global",
  "go.goroot": "/Users/xuzhiqiang/.gvm/gos/go1.13",
```
![image](https://user-images.githubusercontent.com/1265027/78468293-1bbe5d80-7749-11ea-9b2e-c97a7808ef67.png)

The "run test" works, but "debug test" fails:

```
# runtime/internal/atomic
compile: version "go1.13" does not match go tool version "go1.12"
# github.com/google/go-cmp/cmp/internal/diff
compile: version "go1.13" does not match go tool version "go1.12"
# math/bits
compile: version "go1.13" does not match go tool version "go1.12"
# unicode/utf8
compile: version "go1.13" does not match go tool version "go1.12"
```

Not sure if it's a bug of gvm, or vscode?

**Comment by thoroc** [comment]
```gvm use go1.13 --default``` should allow vscode to find the correct version installed with GVM.
