### ISSUE TITLE
gvm install go1.1.2 on OS X 10.9 Mavericks ERROR

### ISSUE THREAD

**Issue by ghost** [moovweb/gvm#36]
```
$ GCC=clang go get -tags zmq_3_x github.com/alecthomas/gozmq
# github.com/alecthomas/gozmq
clang: warning: argument unused during compilation: '-pthread'
# github.com/alecthomas/gozmq
clang: error: no such file or directory: 'libgcc.a'
```

MAYBE

```
export CGO_ENABLED=0
```

**Comment by juvenal** [comment]
I'm a little late on this, but I bumped into this problem when trying to install Go 1.0.3 and 1.1.2 on OS X El Capitan (10.11). It fails at Go build stage. The fix was to do the following on GVM:

```
# CGO_ENABLED=0 gvm install go1.0.3
```
This was enough to allow the build to complete and give a usable Go version ;-)
