### ISSUE TITLE
command not found: gvm

### ISSUE THREAD

**Issue by hzb** [moovweb/gvm#374]
Hello,

First time to find this project, awesome and thanks. There's a bug.

#### Description

`command not found: gvm` if the iTerm is closed then reopen.

#### Reproduce

- Install `gvm`

- It works.

- Exit iTerm and reopen it.

- run `gvm` command, such as `gvm version`, you will get the error information `command not found: gvm`

#### More details

- iTerm 2 (Build 3.4.4)

- Ohmyzsh

- macOS Big Sur 11.2.3 (20D91)

#### Temporary solution

Run `source /Users/<Username>/.gvm/scripts/gvm` again. It will work.

**Comment by hzb** [comment]
I found the reason and fixed.

**Comment by shwetasah-cape** [comment]
Hi @tourcoder . I am facing the same issue. How did you fix it?

**Comment by tourcoder** [comment]
Sorry @shwetasah-cape, I didn't use it anymore. I fixed the issue, but didn't work well. Instead, I am trying to write a simple one which is enough to me, [/tourcoder/glv](https://github.com/tourcoder/glv).

You can search on GitHub, there're  excellent tools of this kind, good luck.

**Comment by dgutt17** [comment]
I know this is closed but this is how I fixed the issue for myself. 
In my bash_profile, I added this:
`source "/Users/dangutt/.gvm/scripts/gvm"`. You can also try your bashrc file.
