### ISSUE TITLE
Issues on OSX

### ISSUE THREAD

**Issue by petems** [moovweb/gvm#38]
Hi! Cool project :+1: 

I notice you don't mention use on OSX, is it supported? If so, I'm having this issue: 

``` bash
$ gvm install go1
Installing go1...
 * Compiling...
ERROR: Failed to compile
ERROR: Failed to use installed version
```

Is there a way to turn verbosity up so I can see the full stack trace and figure out what's going on?

**Comment by brunobatista** [comment]
+1 (Yosemite)

**Comment by offero** [comment]
I am having this problem also, please commit.

**Comment by BenKnigge** [comment]
Several years have passed since the last comment on this issue. Is this still a problem?

**Comment by kevinjamescasey** [comment]
I seem to be having this same problem with v1.0.22 on Moajave 10.14.6. The error message now informs you where to find the logs but the logs look identical at a quick scan. The described fix to the scripts no longer seems to make sense because the scripts have probably changed.
