### ISSUE TITLE
zsh: = not found

### ISSUE THREAD

**Issue by jacobintern** [moovweb/gvm#440]
When I clone gvm into my mac, it always say "zsh: = not found", and i found my .gvm/scripts/ folder dosen't have any gvm file in there.
<img width="1125" alt="image" src="https://github.com/moovweb/gvm/assets/25577606/2cf19816-8afb-4b25-a875-de6e9cb83faa">

this is my .zshrc setting
<img width="802" alt="image" src="https://github.com/moovweb/gvm/assets/25577606/23fd783b-4ec5-45f4-ac24-7a8871e27b65">

and I can't find any gvm in scripts folder
<img width="1110" alt="image" src="https://github.com/moovweb/gvm/assets/25577606/aaf1b9bf-871f-48c9-aa11-50cec0daf6a0">

**Comment by goFrendiAsgard** [comment]
Can you make sure that you use `zsh`?

Try to invoke `echo $SHELL` and `which zsh`.

![image](https://github.com/moovweb/gvm/assets/883662/7170ed5a-9c12-4b26-bb1f-039befac48c1)

If `which zsh` yield error, make sure you have `$PATH` set correctly.

```bash
echo $PATH
```

You should have `/usr/bin` in your `PATH`.

If `$PATH` yield incorrect result, try to comment `[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh` in your `~/.zshrc`

**Comment by RangerCD** [comment]
Same issue here, either my workstation with Manjaro, or my steamdeck.
`which zsh` and `echo $SHELL` point to the same path `/usr/bin/zsh`

**Comment by jacobintern** [comment]
@goFrendiAsgard I am sure that I use zsh.
but I can use bash version command install gvm in my zsh shell ...

**Comment by RangerCD** [comment]
This issue is related to line 115 here:  

https://github.com/moovweb/gvm/blob/dd652539fa4b771840846f8319fad303c7d0a8d2/binscripts/gvm-installer#L115C22-L115C22

Since I don't care about `.bashrc` or `.bash_profile`, I just replace this line with dummy `echo`, then the installer works fine.

**Comment by RangerCD** [comment]
> This issue is related to line 115 here:
> 
> https://github.com/moovweb/gvm/blob/dd652539fa4b771840846f8319fad303c7d0a8d2/binscripts/gvm-installer#L115C22-L115C22
> 
> Since I don't care about `.bashrc` or `.bash_profile`, I just replace this line with dummy `echo`, then the installer works fine.

Or maybe also append the newly added line in `.zshrc` to `.bashrc` would be better.

**Comment by adonespitogo** [comment]
I can confirm @RangerCD 's solution works.

**Comment by samsamm777** [comment]
+1 I have this issue too...

`➜  ~ echo $0
-zsh
➜  ~ zsh < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
Cloning from https://github.com/moovweb/gvm.git to /Users/XXXXX/.gvm
zsh: = not found`

**Comment by ashaffah** [comment]
I have the same problem here

**Comment by RangerCD** [comment]
#442 should fix this issue

**Comment by ankitcharolia** [comment]
@RangerCD @Ashaffah @samsamm777 @adonespitogo @jacobintern @goFrendiAsgard: kindly try out this one. it supports `bash` and `zsh` :  https://github.com/ankitcharolia/goenv
