### ISSUE TITLE
panic: invalid path: 'css/bootstrap.min.css'

### ISSUE THREAD

**Issue by poka-IT** [moovweb/gvm#458]
I use go1.20

When use this command:

`go run brig.go`

from develop, I got this error

```
panic: invalid path: 'css/bootstrap.min.css'

goroutine 1 [running]:
github.com/phogolabs/parcello.AddResource({0xc0007ca000, 0x155ab9, 0x155ab9})
	/home/test/go/pkg/mod/github.com/phogolabs/parcello@v0.8.2/manager.go:53 +0xef
github.com/sahib/brig/gateway/static.init.0()
	/home/test/Bureau/brig/gateway/static/resource.go:9 +0x65
exit status 2
```

**Comment by poka-IT** [comment]
fix here: https://github.com/sahib/brig/pull/123

**Comment by chungyan5** [comment]
hi [poka-IT](https://github.com/poka-IT), 

Any solution for this issue? i am a newbie as I am trying to compile and run brig, it comes out this error exactly same to you. Pls give me some hints how to resolve this issue.

**Comment by chungyan5** [comment]
hi Poka-IT, 

i find your [issue](https://github.com/sahib/brig/pull/123/files), then i get your latest code to compile, it works now. Thanks your code.

**Comment by chungyan5** [comment]
hi Poka-IT,

I wonder how you get it works, i try the steps as"
- `cd gateway/static/`
- `go generate ./...`

no error and have a outcome of resource.go, but staill same error, "panic: invalid path: 'css/bootstrap.min.css'"

**Comment by chungyan5** [comment]
Finally, i can compiled and work now. 

The actions is: i go down the Go version from 1.23(latest) to ~3 yrs old, "go version go1.16.10 linux/amd64", then everything works now.
