### ISSUE TITLE
.gvmrc Support

### ISSUE THREAD

**Issue by pfeairheller** [moovweb/gvm#49]
This is a great project, and I can see myself using this to vendor my dependencies.

Are there any plans or thoughts around adding .gvmrc support like .rvmrc from RVM?  I am working on multiple Go projects at the moment, and auto switching between pkgsets when I switch directories would be fantastic.

Thanks,
-Phil

**Comment by brunobatista** [comment]
+1

**Comment by 13k** [comment]
:+1:

I use [chruby](https://github.com/postmodern/chruby) to manage ruby versions, so another source of inspiration could be its auto switching feature.

It looks pretty simple: https://github.com/postmodern/chruby/blob/master/share/chruby/auto.sh

I'm using a [scrappy modified version](https://gist.github.com/13k/964039295699086c4593) of it and it seems to be working ok (it only supports `.go-version`).

**Comment by markeissler** [comment]
I think this issue should tie in with #219.

**Comment by markeissler** [comment]
I've gone ahead and implemented support for .go-version and .go-pkgset (similar to .ruby-version and .ruby-gemset). See #219 .

This should cover the use case presented by @pfeairheller. The patch will also support coexistence with rvm. Not sure about implementing support for .gemrc at this point, although maybe in the future at least to support tweaking of certain gvm settings.

**Comment by BenKnigge** [comment]
I'm going to close this issue and plan on implementing something using go mod as mentioned in 

https://github.com/moovweb/gvm/issues/219
