### ISSUE TITLE
Go Install Error

### ISSUE THREAD

**Issue by marjinal1st** [moovweb/gvm#97]
I'm using Mint 17 Cinnamon (Ubuntu 14.04 based) with **zsh 5.0.2** shell. All dependencies are installed.

Tried to install:

``` bash
$ gvm install go1
Installing go1...
 * Compiling...
ERROR: Failed to compile. Check the logs at /home/marjinal1st/.gvm/logs/go-go1-compile.log
ERROR: Failed to use installed version
```

Log file: **.gvm/logs/go-go1-compile.log**:

```
# Building C bootstrap tool.
cmd/dist

# Building compilers and Go bootstrap tool for host, linux/amd64.
lib9
libbio
libmach
misc/pprof
cmd/addr2line
cmd/cov
cmd/nm
cmd/objdump
cmd/pack
cmd/prof
cmd/cc
/home/marjinal1st/.gvm/gos/go1/src/cmd/cc/funct.c: In function ‘dclfunct’:
/home/marjinal1st/.gvm/gos/go1/src/cmd/cc/funct.c:273:13: error: iteration 94u invokes undefined behavior [-Werror=aggressive-loop-optimizations]
   f->sym[o] = S;
             ^
/home/marjinal1st/.gvm/gos/go1/src/cmd/cc/funct.c:272:2: note: containing loop
  for(o=0; o<sizeof(f->sym); o++)
  ^
cc1: all warnings being treated as errors
go tool dist: FAILED: gcc -Wall -Wno-sign-compare -Wno-missing-braces -Wno-parentheses -Wno-unknown-pragmas -Wno-switch -Wno-comment -Werror -fno-common -ggdb -O2 -c -m64 -I /home/marjinal1st/.gvm/gos/go1/include -I /home/marjinal1st/.gvm/gos/go1/src/cmd/cc -o $WORK/funct.o /home/marjinal1st/.gvm/gos/go1/src/cmd/cc/funct.c
```

Any ideas?

**Comment by opennota** [comment]
The same here. Gentoo, bash 4.2.

    # Building C bootstrap tool.
    cmd/dist
    
    # Building compilers and Go bootstrap tool for host, linux/amd64.
    lib9
    libbio
    libmach
    misc/pprof
    cmd/addr2line
    cmd/cov
    cmd/nm
    cmd/objdump
    cmd/pack
    cmd/prof
    cmd/cc
    /home/opennota/.gvm/gos/go1/src/cmd/cc/funct.c: In function 'dclfunct':
    /home/opennota/.gvm/gos/go1/src/cmd/cc/funct.c:273:13: error: iteration 94u invokes undefined behavior [-Werror=aggressive-loop-optimizations]
       f->sym[o] = S;
                 ^
    /home/opennota/.gvm/gos/go1/src/cmd/cc/funct.c:272:2: note: containing loop
      for(o=0; o<sizeof(f->sym); o++)
      ^
    cc1: all warnings being treated as errors
    go tool dist: FAILED: gcc -Wall -Wno-sign-compare -Wno-missing-braces -Wno-parentheses -Wno-unknown-pragmas -Wno-switch -Wno-comment -Werror -fno-common -ggdb -O2 -c -m64 -I /home/opennota/.gvm/gos/go1/include -I /home/opennota/.gvm/gos/go1/src/cmd/cc -o $WORK/funct.o /home/opennota/.gvm/gos/go1/src/cmd/cc/funct.c

`gvm install go1.4` and `gvm install go1.3` both worked. I think the issue should be reopened and fixed.

**Comment by lpryszcz** [comment]
same here, `gvm install go1` failed, but `gvm install go1.4` worked fine

**Comment by crawfordcomeaux** [comment]
Same issue. Tried in Ubuntu 14.04 x64 with gcc 4.8, 4.9, and 5. `gvm install go1.4` worked.

**Comment by jiahui-qin** [comment]
i am use ubuntu-18.04
and  `gvm install go1.4` failed, pls help me!

`root@tsn-dev-env-ubuntu-18:~/.gvm/gos# cat  /root/.gvm/logs/go-go1.4-compile.log
# Building C bootstrap tool.
cmd/dist

# Building compilers and Go bootstrap tool for host, linux/amd64.
lib9
/root/.gvm/gos/go1.4/src/lib9/fmt/fltfmt.c: In function '__efgfmt':
/root/.gvm/gos/go1.4/src/lib9/fmt/fltfmt.c:437:5: error: this statement may fall through [-Werror=implicit-fallthrough=]
   if(ndigits > prec) {
     ^
/root/.gvm/gos/go1.4/src/lib9/fmt/fltfmt.c:451:2: note: here
  default:
  ^~~~~~~
cc1: all warnings being treated as errors
go tool dist: FAILED: gcc -Wall -Wstrict-prototypes -Wextra -Wunused -Wno-sign-compare -Wno-missing-braces -Wno-parentheses -Wno-unknown-pragmas -Wno-switch -Wno-comment -Wno-missing-field-initializers -Werror -fno-common -ggdb -pipe -Wuninitialized -O2 -fmessage-length=0 -c -m64 -I /root/.gvm/gos/go1.4/include -DPLAN9PORT -I /root/.gvm/gos/go1.4/src/lib9 -o $WORK/fltfmt.o /root/.gvm/gos/go1.4/src/lib9/fmt/fltfmt.c
`
